### ISSUE TITLE
 Model component to show "Copied to clipboard" does not disappear after 2 seconds

### ISSUE THREAD

**Issue by cjstyles6** [cjstyles6/Password-Generator#2]
When the user clicks the clipboard icon to copy the generated password, a Model component is displayed to show a "Copied to clipboard" message. However, this component does not automatically disappear after 2 seconds as intended.

Expected behavior:
The Model component should automatically disappear/unmount itself after 2 seconds so the message is only briefly displayed.

**Comment by Strange-Quark-007** [comment]
I was not able to find Mdel component in the repo 

The way you do that 
use a state showModel set it to false as default
add onClick function to model
in the function  setShowModel to true 
and a setTimeout function to reset state of showModel to false after few ms.

then simply `showModel && <Model>` in render function where you need to show it.

**Comment by cjstyles6** [comment]
Alright thank you so much

**Comment by cjstyles6** [comment]
but just incase i can't implement it would you help cuz i'm actually new to react and I'm still trying to learn some things

**Comment by marcoarnulfo** [comment]
I created a little div that does what you asked! then you decide whether to make it a component :)
I noticed that your main is "broken" in production, because it cannot find the import of your Model.
I opened a pull request with the fix

**Comment by cjstyles6** [comment]
@marcoarnulfo Thanks

**Comment by cjstyles6** [comment]
@marcoarnulfo please how do i add/see the changes you've made on my local file

**Comment by marcoarnulfo** [comment]
After you merge into master/main, do git pull and have everything updated

**Comment by cjstyles6** [comment]
ok thanks

**Comment by marcoarnulfo** [comment]
@cjstyles6 You can close the issue! I am available to collaborate and give my help btw!

**Comment by cjstyles6** [comment]
Yh sure thanks, I'm working on another project and I'll get to you if I need any help

**Comment by cjstyles6** [comment]
@marcoarnulfo would it be possible if you could help me with my repo i just created
